version: '3'

services:
  # Docker Hubにあるpostgresqlイメージからコンテナを作る
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  # カレントディレクトリにあるDockerfileからコンテナを作る
  web:
    build: .
    # djangoの初期設定と起動
    command: >
      sh -c "pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py custom_createsuperuser --username admin --email admin@example.com --password admin &&
      python manage.py runserver 0.0.0.0:80"
    # ホストPCの80番ポートにデータが来た時、Dockerコンテナの80番ポートにデータを回すように設定
    ports:
      - "80:80"
    # DBが出来てからコンテナを作る
    depends_on:
      - db